### PR TITLE
support no dot git

### PR DESCRIPTION
**Pull request by SeanTConrad**
Fixes bug for remote repos with no .git (Azure) and local repos with no .git in folder name.

### CODE REVIEW

**Review by aylusltd — CHANGES_REQUESTED** [review]
Add some test cases so this doesn't get broken next time. Have a feeling it's gonna get modified again soon.

**Comment by SeanTConrad** [comment]
@aylusltd Added a "test_local" unit test using the already existing folder "tsx_test" but adding it to config.localrepos and running scanRepos.

Also created a public Azure Dev Ops repo with one helloworld file. Added the SSH URL to str_conf.yaml

Two blockers there. First, there has to be a one time acceptance of the RSA key fingerprint. Second, test environment will need Azure SSH keys.

The authenticity of host 'ssh.dev.azure.com (52.228.82.18)' can't be established.
RSA key fingerprint is SHA256:ohD8VZEXGWo6Ez8GSEJQ9WpafgLFsOfLOtGGQCQo6Og.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes

**Comment by aylusltd** [comment]
add `ssh-keyscan -H ssh.dev.azure.com >> ~/.ssh/known_hosts` to the workflow before pytest

**Comment by SeanTConrad** [comment]
Added:
`ssh-keyscan -H ssh.dev.azure.com >> ~/.ssh/known_hosts`
To line 90 of release.yaml. Not sure if that's the correct place.

**Review by aylusltd — APPROVED** [review]

**Pull request merged**
